name: blog.pilatesarea.com
favicon: null
layout_spectrum: 0.4577635247260332
typography_spectrum: 0.6521600720006973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7802647615317255
  lightness: 0.8395294749643654
  saturation: 0.8270960440859199
  rhythmicContrast: 0.6021796257700771
purpose: []
